apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vault-secret-webhook
  namespace: flux-system
spec:
  targetNamespace: vault-infra
  interval: 24h
  timeout: 10m
  releaseName: vault-infra
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: vault-secrets-webhook
        namespace: flux-system
      chart: vault-secrets-webhook
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3