apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  interval: 24h
  timeout: 10m
  releaseName: cert-manager
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      chart: cert-manager
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    installCRDs: true