apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  targetNamespace: prometheus
  interval: 24h
  timeout: 10m
  releaseName: prometheus
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      chart: kube-prometheus-stack
      version: 65.2.0
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      createAggregateClusterRoles: true
    alertmanager:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - alertmanager.example.com
        paths:
          - /
    grafana:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - grafana.example.com
        paths:
          - /
      sidecar:
        datasources:
          url: "http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090"
    prometheus:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - prometheus.example.com
        paths:
          - /
      prometheusSpec:
        ruleSelectorNilUsesHelmValues: true
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        prometheusExternalLabelNameClear: false
        retention: 1d