apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  targetNamespace: vault
  interval: 24h
  timeout: 10m
  releaseName: vault
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: yandex-vault
        namespace: flux-system
      chart: vault
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    server:
       ingress:
         enabled: true
         annotations:
         ingressClassName: "nginx"
         hosts:
           - host: vault.example.com
         tls: []
       affinity: ""
       ha:
          enabled: true
          raft:
             enabled: true
             setNodeId: true
             config: |
                ui = true
                cluster_name = "vault-integrated-storage"
                storage "raft" {
                   path    = "/vault/data/"
                }
    
                listener "tcp" {
                   address = "[::]:8200"
                   cluster_address = "[::]:8201"
                   tls_disable = "true"
                }
                service_registration "kubernetes" {}